networks:
  customer-test:
    driver: bridge

volumes:
  customer-db:
    driver: local
    name: "customer-db"

services:
  customer-db:
    image: mysql/mysql-server:8.0.21
    restart: on-failure
    container_name: "customer-mysql"
    volumes:
      - customer-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "customer"
      MYSQL_PASSWORD: "password"
    ports:
      - "33306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "customer-api"
    restart: on-failure
    volumes:
      - ./:/home/customer/app
    environment:
      DATABASE_URL: "mysql://customer:password@customer-db:3306/customer?serverVersion=8.0.21"
      TEST_DATABASE_URL: "mysql://customer:password@customer-db:3306/customer_test?serverVersion=8.0.21"
      APP_SECRET: "95cfa05fb4d9ea187ca8415aa68fef3e"
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    expose:
      - 8000





